### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by sirackerman** [BalveerSinghYT/YDM-SLAM#1]
Has it been tested on other datasets like KITTI? . Do you have any insight on how it performs in outdoor environement with high dynamism?

**Comment by BalveerSinghYT** [comment]
Hi Ariano,

No, I didn't test it on the KITTI dataset. YDM-SLAM is the enhanced version of ORB-SLAM3 and was implemented only for indoor environments.

**Comment by sirackerman** [comment]
oh alright, thank you for the response.
